function Hd = design_g0(N,Fs)
%DESIGN_g0 Returns a discrete-time filter object.

%
% M-File generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
%
% Generated on: 05-Jan-2012 13:03:37
%

%N  = 32;     % Order
B  = 1;      %
% Fs = 16000;  % Sampling Frequency

% First Frequency Vector
F1 = [0  Fs/2];

% First Amplitude Vector
A1 = [1 1];

h = fdesign.arbmag('N,B,F,A', N, B, F1, A1, Fs);

Hd = design(h, 'firls');

set(Hd, 'Arithmetic', 'fixed', ...
    'InputWordLength', 16, ...
    'InputFracLength', 15, ...
    'CoeffWordLength', 16, ...
    'CoeffAutoScale', true, ...
    'FilterInternals', 'Fullprecision');

% [EOF]
